services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - vokabeltrainer-net
    depends_on:
      - db
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    networks:
      - vokabeltrainer-net
    depends_on:
      - backend

  db:
    image: postgres:17
    environment:
      POSTGRES_USER: nodepg
      POSTGRES_PASSWORD: nodepg
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - vokabeltrainer-net
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db/init-scripts:/docker-entrypoint-initdb.d

networks:
  vokabeltrainer-net:

volumes:
  postgres-data: